import { Match, BetsFeedItem, SportCategory } from '@/types/sports';
import { Globe } from 'lucide-react';

export const sportCategories: { id: SportCategory; name: string; icon: string; count?: number }[] = [
  { id: 'soccer', name: 'Soccer', icon: '⚽', count: 899 },
  { id: 'cricket', name: 'Cricket', icon: '🏏', count: 45 },
  { id: 'tennis', name: 'Tennis', icon: '🎾', count: 120 },
  { id: 'basketball', name: 'Basketball', icon: '🏀', count: 85 },
  { id: 'counter-strike', name: 'Counter-Strike', icon: '🎮', count: 32 },
  { id: 'dota2', name: 'Dota 2', icon: '⚔️', count: 18 },
  { id: 'league-of-legends', name: 'League of Legends', icon: '🎯', count: 24 },
  { id: 'volleyball', name: 'Volleyball', icon: '🏐', count: 56 },
  { id: 'table-tennis', name: 'Table Tennis', icon: '🏓', count: 78 },
  { id: 'ice-hockey', name: 'Ice Hockey', icon: '🏒', count: 42 },
];

export const popularMatches: Match[] = [
  {
    id: '1',
    league: 'T20 Premier League',
    country: 'India',
    startTime: 'Today, 14:30',
    isLive: false,
    homeTeam: { id: 't1', name: 'Gujarat Giants' },
    awayTeam: { id: 't2', name: 'Mumbai Indians' },
    odds: { home: 2.00, draw: 0, away: 1.65 },
  },
  {
    id: '2',
    league: 'T20 Internationals',
    country: 'International',
    startTime: 'Today, 19:00',
    isLive: false,
    homeTeam: { id: 't3', name: 'Sri Lanka' },
    awayTeam: { id: 't4', name: 'England' },
    odds: { home: 1.80, draw: 0, away: 1.62 },
  },
  {
    id: '3',
    league: "ICC Women's World Cup Qualifier",
    country: 'International',
    startTime: '1 INPL 4.4 OV',
    isLive: true,
    liveTime: '1st Innings',
    homeTeam: { id: 't5', name: 'Ireland' },
    awayTeam: { id: 't6', name: 'Netherlands' },
    odds: { home: 1.85, draw: 0, away: 4.5 },
  },
  {
    id: '4',
    league: "ICC Women's World Cup Qualifier",
    country: 'International',
    startTime: '1 INL 2.2 OV',
    isLive: true,
    liveTime: '1st Innings',
    homeTeam: { id: 't7', name: 'Bangladesh' },
    awayTeam: { id: 't8', name: 'Scotland' },
    odds: { home: 1.91, draw: 0, away: 1.07 },
  },
];

export const liveMatches: Match[] = [
  {
    id: 'l1',
    league: 'Liga Betis',
    country: 'Angola',
    startTime: '71\'',
    isLive: true,
    liveTime: '2nd half',
    homeTeam: { id: 'lt1', name: 'Independiente Candombe Benta' },
    awayTeam: { id: 'lt2', name: 'Alto Zambeze' },
    odds: { home: 3.45, draw: 3.0, away: 2.35 },
    additionalMarkets: [
      {
        name: 'Double chance',
        options: [
          { label: 'Sportivo 2 de', value: '1X', odds: 1.89 },
          { label: 'Sportivo 2 de', value: '12', odds: 1.19 },
          { label: 'draw or Olim', value: 'X2', odds: 1.19 },
        ],
      },
      {
        name: 'Total',
        options: [
          { label: 'over 2.5', value: 'over', odds: 1.61 },
          { label: 'under 2.5', value: 'under', odds: 2.2 },
        ],
      },
      {
        name: 'Handicap',
        options: [
          { label: '(0.5) Sportivo 2 de Mayo', value: 'h1', odds: 1.91 },
          { label: '(-0.5) Olimpia Asuncion', value: 'h2', odds: 1.74 },
        ],
      },
    ],
  },
  {
    id: 'l2',
    league: 'Liga Pro Konstantinoples',
    country: 'Russia',
    startTime: '45\'',
    isLive: true,
    liveTime: '2nd half',
    homeTeam: { id: 'lt3', name: 'Ismmed-pro' },
    awayTeam: { id: 'lt4', name: 'Djaber-pro' },
    odds: { home: 1.55, draw: 3.8, away: 4.2 },
  },
  {
    id: 'l3',
    league: '3rd MixFootbal Liga Pro',
    country: 'Russia',
    startTime: '23\'',
    isLive: true,
    liveTime: '1st half',
    homeTeam: { id: 'lt5', name: 'Gladiator-pro' },
    awayTeam: { id: 'lt6', name: 'Twentytwo-pro' },
    odds: { home: 3.5, draw: 3.6, away: 2.35 },
  },
  {
    id: 'l4',
    league: 'England FA Cup',
    country: 'eSoccer',
    startTime: '62\'',
    isLive: true,
    liveTime: '2nd half',
    homeTeam: { id: 'lt7', name: 'Man. United (F)' },
    awayTeam: { id: 'lt8', name: 'Arsenal FC (F)' },
    odds: { home: 2.1, draw: 3.4, away: 3.1 },
  },
];

export const upcomingMatches: Match[] = [
  {
    id: 'u1',
    league: 'A-League',
    country: 'Australia',
    startTime: 'Today, 16:00',
    isLive: false,
    homeTeam: { id: 'ut1', name: 'Wellington Phoenix FC' },
    awayTeam: { id: 'ut2', name: 'Melbourne City FC' },
    odds: { home: 3.5, draw: 3.6, away: 2.66 },
  },
  {
    id: 'u2',
    league: 'Bengal Super League',
    country: 'India',
    startTime: 'Today, 18:00',
    isLive: false,
    homeTeam: { id: 'ut3', name: 'Howrah Hooghly Warriors' },
    awayTeam: { id: 'ut4', name: 'Sundarbans Bengal Ants' },
    odds: { home: 3.56, draw: 3.35, away: 3.5 },
  },
  {
    id: 'u3',
    league: 'Liga 1',
    country: 'Indonesia',
    startTime: 'Today, 14:00',
    isLive: false,
    homeTeam: { id: 'ut5', name: 'Persik Kediri' },
    awayTeam: { id: 'ut6', name: 'Bali United' },
    odds: { home: 2.8, draw: 3.3, away: 2.55 },
  },
  {
    id: 'u4',
    league: 'Liga 1',
    country: 'Indonesia',
    startTime: 'Today, 14:00',
    isLive: false,
    homeTeam: { id: 'ut7', name: 'Persita Tangerang' },
    awayTeam: { id: 'ut8', name: 'Persija Jakarta' },
    odds: { home: 4.0, draw: 3.15, away: 1.95 },
  },
];

export const eventBuilderMatches: Match[] = [
  {
    id: 'eb1',
    league: 'Primera Division Reserve',
    country: 'Paraguay',
    startTime: 'Today, 16:00',
    isLive: false,
    homeTeam: { id: 'ebt1', name: 'Sportivo 2 de Mayo' },
    awayTeam: { id: 'ebt2', name: 'Olimpia Asuncion' },
    odds: { home: 4.7, draw: 4.0, away: 1.68 },
    additionalMarkets: [
      {
        name: 'Double chance',
        options: [
          { label: 'Sportivo 2 de', value: '1X', odds: 1.89 },
          { label: 'Sportivo 2 de', value: '12', odds: 1.19 },
          { label: 'draw or Olim', value: 'X2', odds: 1.19 },
        ],
      },
      {
        name: 'Total',
        options: [
          { label: 'over 2.5', value: 'over', odds: 1.61 },
          { label: 'under 2.5', value: 'under', odds: 2.2 },
        ],
      },
      {
        name: 'Handicap',
        options: [
          { label: '(0.5) Sportivo 2 de Mayo', value: 'h1', odds: 1.91 },
          { label: '(-0.5) Olimpia Asuncion', value: 'h2', odds: 1.74 },
        ],
      },
      {
        name: 'Both teams to score',
        options: [
          { label: 'Yes', value: 'yes', odds: 1.85 },
          { label: 'No', value: 'no', odds: 1.95 },
        ],
      },
    ],
  },
  {
    id: 'eb2',
    league: 'UAAP Championship',
    country: 'Philippines',
    startTime: 'Today, 16:00',
    isLive: false,
    homeTeam: { id: 'ebt3', name: 'UP Fighting Maroons' },
    awayTeam: { id: 'ebt4', name: 'Green Archers United' },
    odds: { home: 1.83, draw: 3.2, away: 4.2 },
  },
  {
    id: 'eb3',
    league: 'Primera Division Reserve',
    country: 'Paraguay',
    startTime: 'Today, 16:00',
    isLive: false,
    homeTeam: { id: 'ebt5', name: 'Libertad Asuncion' },
    awayTeam: { id: 'ebt6', name: 'Sportivo Ameliano' },
    odds: { home: 1.93, draw: 3.35, away: 3.55 },
  },
  {
    id: 'eb4',
    league: '1st League',
    country: 'DR Congo',
    startTime: 'Today, 16:30',
    isLive: false,
    homeTeam: { id: 'ebt7', name: 'Groupe Bazano' },
    awayTeam: { id: 'ebt8', name: 'Lubumbashi Sport' },
    odds: { home: 2.88, draw: 3.1, away: 2.32 },
  },
  {
    id: 'eb5',
    league: 'Liga Bet',
    country: 'Israel',
    startTime: 'Today, 16:30',
    isLive: false,
    homeTeam: { id: 'ebt9', name: 'Hapoel Seger Shalom' },
    awayTeam: { id: 'ebt10', name: 'Ironi Beit Shemesh' },
    odds: { home: 3.55, draw: 2.8, away: 1.81 },
  },
  {
    id: 'eb6',
    league: 'Dhivehi Premier League',
    country: 'Maldives',
    startTime: 'Today, 16:30',
    isLive: false,
    homeTeam: { id: 'ebt11', name: 'Victory SC' },
    awayTeam: { id: 'ebt12', name: 'TC Sports Club' },
    odds: { home: 1.72, draw: 3.45, away: 4.4 },
  },
  {
    id: 'eb7',
    league: 'Alkass International Cup (2x40)',
    country: 'International',
    startTime: 'Today, 16:45',
    isLive: false,
    homeTeam: { id: 'ebt13', name: 'Aspire Academy U17' },
    awayTeam: { id: 'ebt14', name: 'Mohammed VI FA' },
    odds: { home: 1.89, draw: 3.4, away: 3.65 },
  },
  {
    id: 'eb8',
    league: 'Premier Division League',
    country: 'Iraq',
    startTime: 'Today, 17:00',
    isLive: false,
    homeTeam: { id: 'ebt15', name: 'Kadhimiya' },
    awayTeam: { id: 'ebt16', name: 'Al Nasiriya' },
    odds: { home: 2.94, draw: 2.66, away: 2.84 },
  },
];

export const betsFeedData: BetsFeedItem[] = [
  {
    id: 'bf1',
    sport: 'all',
    event: 'RFK Ahmat Grozny - FK Vardar Skopje',
    //  icon:Globe,
    outcome: 'under 1.5, Total',
    odds: 2.080,
    stake: '15.00 $',
    potentialWin: '31.20 $',
    user: '***vol',
    type: 'single',
  },
  {
    id: 'bf2',
    sport: 'soccer',
    event: 'Vici Gaming - Team Nemesis',
     //  icon:Globe,
    outcome: 'Team Nemesis, Winner',
    odds: 2.610,
    stake: '83.00 USDT',
    potentialWin: '216.63 USDT',
    user: '***woz',
    type: 'single',
  },
  {
    id: 'bf3',
    sport: 'soccer',
    event: 'Vici Gaming - Team Nemesis',
     //  icon:Globe,
    outcome: 'Vici Gaming, Third map - winner',
    odds: 1.360,
    stake: '0.16000000 BNB',
    potentialWin: '0.18500000 BNB',
    user: '***KUN',
    type: 'single',
  },
  {
    id: 'bf4',
    sport: 'tennis',
    event: 'Artur Khudorozok - Avtomobilist Yekaterinburg',
     //  icon:Globe,
    outcome: 'over 1.5, Avtomobilist Yekaterinburg total',
    odds: 1.479,
    stake: '4200.00 $',
    potentialWin: '6574.00 $',
    user: '***wol',
    type: 'single',
  },
  {
    id: 'bf5',
    sport: 'basketball',
    event: 'PFK Arsenal Tula - PFC Nazaf',
     //  icon:Globe,
    outcome: 'under 1.5, Total',
    odds: 1.950,
    stake: '15.00 $',
    potentialWin: '29.25 $',
    user: '***rol',
    type: 'single',
  },
  {
    id: 'bf6',
    sport: 'counter-strike',
    event: 'Pagula, Jessica - Rybakina, Elena',
     //  icon:Globe,
    outcome: 'Rybakina, Elena (-2.5), Game handicap',
    odds: 1.913,
    stake: '26.00 USDT',
    potentialWin: '49.35 USDT',
    user: '***KUN',
    type: 'single',
  },
  {
    id: 'bf7',
    sport: 'dota2',
    event: 'Bayern (E) - Chelsea FC (E)',
     //  icon:Globe,
    outcome: 'Chelsea FC (E), 1st half - 1x2',
    odds: 4.400,
    stake: '19.00 $',
    potentialWin: '83.60 $',
    user: '***vol',
    type: 'single',
  },
  {
    id: 'bf8',
    sport: 'soccer',
    event: 'Morris, Billy - Bonzi, Benjamin; Vekic, Donna - Zhu, Lin...',
     //  icon:Globe,
    outcome: 'Volodymyr, Yakimenko; Tiutev, Uliana...',
    odds: 9.35,
    stake: '550.67 $',
    potentialWin: '$5,239.61 $',
    user: '***woz',
    type: 'combo',
  },
  {
    id: 'bf9',
    sport: 'volleyball',
    event: 'South Africa - West Indies',
     //  icon:Globe,
    outcome: 'under 350.5, Total runs',
    odds: 1.820,
    stake: '$ 3000.00',
    potentialWin: '$ 5460.00',
    user: '***vol',
    type: 'single',
  },
  {
    id: 'bf10',
    sport: 'ice-hockey',
    event: 'Tikhonov, Evgeny - Xu, Haidong',
    //  icon:Globe,
    outcome: 'Xu, Haidong, Winner',
    odds: 1.800,
    stake: '100.00 $',
    potentialWin: '180.00 $',
    user: '***wol',
    type: 'single',
  },
];
